config/routes.rb
JCDemo::Application.routes.draw do
  resources :cards

  resources :overtimes

  resources :records

  resources :departments

  resources :employees

  resources :terminals

  resources :groups

  resources :task

  resources :project

  root :to => "home#index"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :card_number, :created_at, :employee_id, :id, :lost_at, :update_at

  belongs_to :employee
  has_many :records
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
    mount_uploader :cover, ImageUploader
end

app/models/department.rb
#encoding:utf-8
class Department < ActiveRecord::Base
  include CommonActiveRecord
  attr_accessible :id, :name, :state, :parent_id
  has_many :employees

  #belongs_to :parent,:class_name => 'Department',:foreign_key => 'parent_id'
  #belongs_to :children,:class_name => 'Department',:foreign_key => 'parent_id'


  def parent
    Department.find(self.parent_id).name
  end

  def has_children?
    Department.where("parent_id = ?",self.id).count >=1
  end

  def has_employees?
    self.employees >=1
  end
end

app/models/employee.rb
#encoding:utf-8
class Employee < ActiveRecord::Base
  attr_accessible :birthday, :code, :department_id, :expired_at, :id, :name, :remark, :sex, :state

  belongs_to :department
  has_one :card

  MALE = 1 #男
  FEMALE = 0 #女

  ONJOIB = 1 #在职
  OFFJOIB = 2 #离职
  AWAYJOIB = 3 #出差
  MATERNITYlEAVE = 4 #产假
  PATERNITYlEAVE = 5 #陪产假

  def state_text
    case self.state.to_i
      when  Employee::ONJOIB
        '在职'
      when  Employee::OFFJOIB
        '离职'
      when  Employee::AWAYJOIB
        '出差'
      when  Employee::MATERNITYlEAVE
        '产假'
      when  Employee::PATERNITYlEAVE
        '陪产假'
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :id, :name, :parent_menu_id, :url, :right_id
  include CommonActiveRecord
  belongs_to :right
  belongs_to :parent,:class_name => "Menu",:foreign_key => "parent_menu_id"

  def self.root
    Menu.find 1
  end

  def self.root_menu
    where(parent_menu_id: nil).order("id").all
  end

  def children
    Menu.all :conditions => ['parent_menu_id = ?', self.id]
  end

  def menu_right
    self.right.name
  end

  def parent_menu

  end

end

app/models/overtime.rb
class Overtime < ActiveRecord::Base
  attr_accessible :description, :employee_id, :end_time, :id, :start_time
end

app/models/photo.rb
class Photo < ActiveRecord::Base
    mount_uploader :image, ImageUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  belongs_to :project_creator,:class_name => 'User',:foreign_key => 'creator'
  belongs_to :user
  attr_accessible :creator, :description, :id, :name, :state,:group_id,:project_url
end

app/models/record.rb
#encoding:utf-8
class Record < ActiveRecord::Base
  attr_accessible :id, :in_out, :terminal_ip

  include CommonActiveRecord

  belongs_to :card
  belongs_to :terminal

  ONTIME = 0
  LATE = 1
  ONLEAVE = 2

  def in_out_text
    case self.in_out.to_i
      when 1
        '上班'
      when 2
        '下班'
    end
  end

  def work_state
    case self.created_at < DateTime.new(DateTime.current.year, DateTime.current.month, DateTime.current.day, 8, 30, 0)
      when true
        '正常上班'
      when false
        '迟到'
    end
  end
end

app/models/right.rb
#encoding:utf-8
class Right < ActiveRecord::Base
  attr_accessible :description, :id, :name, :state
  include CommonActiveRecord
  has_many :role_rights
  has_many :roles, :through => :role_rights
  has_one :menu

  def self.all_names
    self.all.collect{|right|[right.name,right.id]}
  end


end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :id, :name
  include CommonActiveRecord
  has_many :role_users
  has_many :users, :through => :role_users
  has_many :role_rights
  has_many :rights, :through => :role_rights

  attr_accessible :name,:description,:state

  accepts_nested_attributes_for :rights

  def enabled?
    self.state == ENABLED
  end

  def disabled?
    self.state == DISABLED
  end

  def used?
    !users.empty?
  end

  def has_right? id
    !self.role_rights.where(right_id: id).blank?
  end
end

app/models/role_right.rb
class RoleRight< ActiveRecord::Base
  belongs_to :role
  belongs_to :right
end

app/models/role_user.rb
class RoleUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project,:counter_cache => true
  attr_accessible :creator, :description, :id, :name, :operation, :state,:project_id
end

app/models/terminal.rb
class Terminal < ActiveRecord::Base
  attr_accessible :id, :name, :remote_id, :state
  include CommonActiveRecord

  has_many :records
end

app/models/user.rb
#encoding:utf-8
class User < ActiveRecord::Base
  include CommonActiveRecord
  attr_accessible :email, :name, :password, :state

  mount_uploader :avatar, ImageUploader
  has_many :role_users
  has_many :roles, through: :role_users
  has_many :projects
  has_one :card


  attr_accessible :name,:description,:state

  def role_name
    self.roles.collect{|role| role.name}.first
  end


end

app/controllers/employees_controller.rb
#encoding:utf-8
class EmployeesController < ApplicationController
  STATES = [["在职",Employee::ONJOIB],["离职",Employee::OFFJOIB,2],["出差",Employee::AWAYJOIB,3],["产假",Employee::MATERNITYlEAVE,4],["陪产假",Employee::PATERNITYlEAVE,5]]
  def index
    @title = "当前位置 员工列表"
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end


  def new
    @title = "当前位置 新增员工资料"
    @states = STATES
    @employee = Employee.new
  end


  def edit
    @title = "当前位置 编辑员工资料"
    @states = STATES
    @employee = Employee.find(params[:id])
  end


  def create
    @employee = Employee.new(params[:employee])
    Employee.transaction do
      @employee.save
    end
    redirect_to :action => :index
  end


  def update
    @employee = Employee.find(params[:id])
    @employee.update_attributes(params[:employee])
    @employee.save
    redirect_to :action => :index
  end


  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
  end

  def query
    @employees = set_paginate Employee.where("name like ?","%#{params[:name]}%")
    render :action => :index
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/employees_helper.rb
#encoding:utf-8
module EmployeesHelper


end

app/helpers/menu_helper.rb
#encoding:utf-8
module MenuHelper
  def show_menu
    content_tag(:div, :class => "menu") do
      content_tag(:div, :class => "side_menuTop") do
        #raw(content_tag(:span,:class => "side_menuLeft"){} +  content_tag(:span,:class=>"side_menuTitle") { link_to "菜单管理","#"} + content_tag(:span,:class=>"side_menuRight"){})
      end
      content_tag(:div,:class=>"side_menu") do
        link_to "菜单1","#"
      end
      content_tag(:div,:class=>"side_menuDown") {}
    end

  end
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/user_helper.rb
module UserHelper
  def user_avatar_tag(user,options = {})
    options[:style] ||= :small
    style = case options[:style].to_s
              when "small" then "30*30"
              when "normal" then "100*100"
              when "large" then "240*240"
              when "tiny" then "20*20"
              else options[:style].to_s
            end
    link_to image_tag(user.avatar(style)),user
  end

  def upyun_form_input_tag(opts = {})
    form_api_key = "THE API KEY"
    opts[:prefix] ||= ""
    opts[:allow_exts] ||= "jpg,jpeg,gif,png"
    opts[:min_length] ||= 0
    opts[:max_length] ||= 200.kilobyte
    opts[:return_url] ||= root_url
    opts[:notify_url] ||= root_url
    opts[:unsharp] ||= false
    opts[:quality] ||= 95
    hash = {
        "bucket" => "rbtest",
        "expiration" => 20.minutes.since.to_i,
        "save-key" => [opts[:prefix],"{year}/{mon}/{filemd5}{.suffix}"].join("/"),
        "allow-file-type" => opts[:allow_exts],
        "content-length-range" => "#{opts[:min_length].to_i},#{opts[:max_length].to_i}",
        "return-url" => opts[:return_url],
        "notify-url" => opts[:notify_url],
        "x-gmkerl-unsharp" => opts[:unsharp],
        "x-gmkerl-quality" => opts[:quality].to_i
    }
    puts "JSON: #{hash.to_json}"
    policy = Base64.encode64(hash.to_json).gsub("\n","")
    sign = Digest::MD5.hexdigest([policy,form_api_key].join("&"))
    raw [tag(:input, :type => "hidden", :name => "policy", :value => policy),tag(:input, :type => :hidden, :name => "signature",:value => sign)].join("\n")
  end
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.datetime_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br />
    <%= f.number_field :department_id %>
  </div>
  <div class="field">
    <%= f.label :remark %><br />
    <%= f.text_field :remark %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :expired_at %><br />
    <%= f.datetime_select :expired_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>编辑员工资料</title>
</head>
<body>
<%= title_bar %>
<%= form_for @employee, {:url => {:action => :update }} do |f| %>
    <fieldset style="width:50%;margin-left:200px;margin-top:90px;height:60%;">
      <legend>编辑资料</legend>
      <table class="resultTable">
        <tr>
          <td align="center">姓名:</td>
          <td><%= f.text_field :name, :size => "30", :class => "input_text" %></td>
          <td align="center">编号:</td>
          <td><%= f.text_field :code, :size => "30", :class => "input_text" %></td>
        </tr>
        <tr>
          <td align="center">性别:</td>
          <td>
            <%= f.radio_button :sex, 1, checked: true %>男 &nbsp;&nbsp;
            <%= f.radio_button :sex, 0 %>女
          </td>
          <td align="center">生日:</td>
          <td><%= f.text_field :birthday, :size => "30", :class => "input_text",:onclick => "WdatePicker()" %></td>
        </tr>
        <tr>
          <td align="center">部门:</td>
          <td>
            <%=f.select :department_id, Department.all.collect{|d|[d.name,d.id]}%>
          </td>
          <td align="center">备注:</td>
          <td><%= f.text_field :remark, :size => "30", :class => "input_text" %></td>
        </tr>
        <tr>
          <td align="center">就职状态:</td>
          <td><%= f.select :state, options_for_select(@states),:size => "30", :class => "input_text"%></td>
          <td align="center">到职日期:</td>
          <td><%= f.text_field :expired_at, :size => "30", :class => "input_text",:onclick => "WdatePicker()"  %></td>
        </tr>
        <tr>
          <td colspan="4" align="right">
            <%= f.submit "更新", :class => "button_blue" %>
            <%= f.button '重置' ,:class => "button_blue" %>
          </td>
        </tr>
      </table>
    </fieldset>
<% end %>
</body>
</html>

app/views/employees/index.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
  <title>职工列表</title>
</head>
<script type="text/javascript">
    $(function () {
//        查找的form提交
        $("#searchUser").click(function(){
            $('#searchForm').submit();
        });
    })
</script>
<body>
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td height="27"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="3" height="27"><%= image_tag("main_42.gif",width:'3',height:'27') %></td>
        <td background="<%= asset_path 'main_43.gif' %>">
          <table width="100%" height="21" border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td style="padding-left:5px; font-size:9pt;"><table border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="3%"><div align="center"><%= image_tag("right01.gif",width:'14',height:'14') %></div></td>
                  <td width="97%" style="font-size:12px; padding-left:10px;" nowrap="nowrap"><%= @title %> </td>
                </tr>
              </table></td>
              <td width="265px" >
                <%= form_tag({:controller => :employees,:action => :query},:name => 'searchForm',:id => 'searchForm')  do%>
                    <span class="search_text" style="font-size: 12px;">职工名称:<%= text_field_tag :name,'',:class => 'input_search' %></span>
                    <table width="50px" border="0" align="right" cellpadding="0" cellspacing="0">
                      <tr>
                        <td width="3px" height="21"><%= image_tag("main_46.gif",width:'3',height:'21') %></td>
                        <td background="<%= asset_path 'main_48.gif' %>"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td>
                              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                  <td><div align="center"><%= image_tag("src.gif",width:'15',height:'13') %></div></td>
                                  <td><div align="center"><span class="STYLE1" id="searchUser" >查找</span></div></td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                        </table>
                        </td>
                      </tr>
                    </table>
                    <td width="3"><%= image_tag("main_51.gif",width:'3',height:'21') %></td>
                    </tr>
                    </table>
                    </td>
                <% end %>
                </tr>
    </table>
    </td>
    <td width="3"><%= image_tag("main_44.gif") %></td>
  </tr>
</table></td>
</tr>
<tr>
  <td valign="top" bgcolor="#FFFFFF" style="border-left:solid 1px #7a99c2; border-bottom:solid 1px #7a99c2; border-right:solid 1px #7a99c2; padding-top:2px; padding-left:3px; padding-right:3px;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td>
        <table class="simpleTable">
          <tr>
            <th  class="tab_firstline">编号</th>
            <th class="tab_firstline">姓名</th>
            <th class="tab_firstline">卡号</th>
            <th class="tab_firstline">性别</th>
            <th class="tab_firstline">生日</th>
            <th class="tab_firstline">所属部门</th>
            <th class="tab_firstline">状态</th>
            <th class="tab_firstline">入职日期</th>
            <th class="tab_firstline">操作</th>
          </tr>
          <% @employees.each do |employee| %>
              <tr>
                <td class="td1"><%= list_index %></td>
                <td class="td1"><%= employee.name %></td>
                <td class="td1"><%= employee.card.card_number %></td>
                <td class="td1"><%= employee.sex.to_i == 1 ? '男' : '女' %></td>
                <td class="td1"><%= employee.birthday.to_date %></td>
                <td class="td1"><%= employee.department.name %></td>
                <td class="td1"><%= employee.state_text %></td>
                <td class="td1"><%= format_datetime employee.created_at %></td>
                <td class="td1">
                  <%= link_to  '[新增]',:action => :new %>&nbsp;&nbsp;&nbsp;&nbsp;
                  <%= link_to  '[编辑]',:action => :edit,:id => employee.id %>&nbsp;&nbsp;&nbsp;&nbsp;
                </td>
              </tr>
          <% end %>
        </table>
      </td>
    </tr>
  </table></td>
</tr>
</table>
</body>
</html>

app/views/employees/new.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>新建员工资料</title>
</head>
<body>
<%= title_bar %>
<%= form_for :employee, {:url => {:action => :create }} do |f| %>
    <fieldset style="width:50%;margin-left:200px;margin-top:90px;height:60%;">
      <legend>新增资料</legend>
      <table class="resultTable">
        <tr>
          <td align="center">姓名:</td>
          <td><%= f.text_field :name, :size => "30", :class => "input_text" %></td>
          <td align="center">编号:</td>
          <td><%= f.text_field :code, :size => "30", :class => "input_text" %></td>
        </tr>
        <tr>
          <td align="center">性别:</td>
          <td>
             <%= f.radio_button :sex, 1, checked: true %>男 &nbsp;&nbsp;
             <%= f.radio_button :sex, 0 %>女
          </td>
          <td align="center">生日:</td>
          <td><%= f.text_field :birthday, :size => "30", :class => "input_text",:onclick => "WdatePicker()" %></td>
        </tr>
        <tr>
          <td align="center">部门:</td>
          <td>
            <%=f.select :department_id, Department.all.collect{|d|[d.name,d.id]}%>
          </td>
          <td align="center">备注:</td>
          <td><%= f.text_field :remark, :size => "30", :class => "input_text" %></td>
        </tr>
        <tr>
          <td align="center">就职状态:</td>
          <td><%= f.select :state, options_for_select(@states),:size => "30", :class => "input_text"%></td>
          <td align="center">到职日期:</td>
          <td><%= f.text_field :expired_at, :size => "30", :class => "input_text",:onclick => "WdatePicker()"  %></td>
        </tr>
        <tr>
          <td colspan="4" align="right">
            <%= f.submit "保存", :class => "button_blue" %>
            <%= f.button '重置' ,:class => "button_blue" %>
          </td>
        </tr>
      </table>
    </fieldset>
<% end %>
</body>
</html>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @employee.id %>
</p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Code:</b>
  <%= @employee.code %>
</p>

<p>
  <b>Sex:</b>
  <%= @employee.sex %>
</p>

<p>
  <b>Birthday:</b>
  <%= @employee.birthday %>
</p>

<p>
  <b>Department:</b>
  <%= @employee.department_id %>
</p>

<p>
  <b>Remark:</b>
  <%= @employee.remark %>
</p>

<p>
  <b>State:</b>
  <%= @employee.state %>
</p>

<p>
  <b>Expired at:</b>
  <%= @employee.expired_at %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>