config/routes.rb
JCDemo::Application.routes.draw do
  resources :cards

  resources :overtimes

  resources :records

  resources :departments

  resources :employees

  resources :terminals

  resources :groups

  resources :task

  resources :project

  root :to => "home#index"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/overtime.rb
class Overtime < ActiveRecord::Base
  attr_accessible :description, :employee_id, :end_time, :id, :start_time
end

app/controllers/overtimes_controller.rb
class OvertimesController < ApplicationController
  # GET /overtimes
  # GET /overtimes.json
  def index
    @overtimes = Overtime.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @overtimes }
    end
  end

  # GET /overtimes/1
  # GET /overtimes/1.json
  def show
    @overtime = Overtime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @overtime }
    end
  end

  # GET /overtimes/new
  # GET /overtimes/new.json
  def new
    @overtime = Overtime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @overtime }
    end
  end

  # GET /overtimes/1/edit
  def edit
    @overtime = Overtime.find(params[:id])
  end

  # POST /overtimes
  # POST /overtimes.json
  def create
    @overtime = Overtime.new(params[:overtime])

    respond_to do |format|
      if @overtime.save
        format.html { redirect_to @overtime, notice: 'Overtime was successfully created.' }
        format.json { render json: @overtime, status: :created, location: @overtime }
      else
        format.html { render action: "new" }
        format.json { render json: @overtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /overtimes/1
  # PUT /overtimes/1.json
  def update
    @overtime = Overtime.find(params[:id])

    respond_to do |format|
      if @overtime.update_attributes(params[:overtime])
        format.html { redirect_to @overtime, notice: 'Overtime was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @overtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /overtimes/1
  # DELETE /overtimes/1.json
  def destroy
    @overtime = Overtime.find(params[:id])
    @overtime.destroy

    respond_to do |format|
      format.html { redirect_to overtimes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/overtimes_helper.rb
module OvertimesHelper
end

app/views/overtimes/_form.html.erb
<%= form_for(@overtime) do |f| %>
  <% if @overtime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@overtime.errors.count, "error") %> prohibited this overtime from being saved:</h2>

      <ul>
      <% @overtime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/overtimes/edit.html.erb
<h1>Editing overtime</h1>

<%= render 'form' %>

<%= link_to 'Show', @overtime %> |
<%= link_to 'Back', overtimes_path %>

app/views/overtimes/index.html.erb
<h1>Listing overtimes</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Employee</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @overtimes.each do |overtime| %>
  <tr>
    <td><%= overtime.id %></td>
    <td><%= overtime.employee_id %></td>
    <td><%= overtime.start_time %></td>
    <td><%= overtime.end_time %></td>
    <td><%= overtime.description %></td>
    <td><%= link_to 'Show', overtime %></td>
    <td><%= link_to 'Edit', edit_overtime_path(overtime) %></td>
    <td><%= link_to 'Destroy', overtime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Overtime', new_overtime_path %>

app/views/overtimes/new.html.erb
<h1>New overtime</h1>

<%= render 'form' %>

<%= link_to 'Back', overtimes_path %>

app/views/overtimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @overtime.id %>
</p>

<p>
  <b>Employee:</b>
  <%= @overtime.employee_id %>
</p>

<p>
  <b>Start time:</b>
  <%= @overtime.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @overtime.end_time %>
</p>

<p>
  <b>Description:</b>
  <%= @overtime.description %>
</p>


<%= link_to 'Edit', edit_overtime_path(@overtime) %> |
<%= link_to 'Back', overtimes_path %>